[tool.poetry]
name = "delta"
version = "0.1.0"
description = ""
authors = ["uname-n"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.4.1"
deltalake = "^0.18.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
